// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvgfrykfprnzkrrqgwlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2Z2ZyeWtmcHJuemtycnFnd2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjc3NDUsImV4cCI6MjA3NDY0Mzc0NX0.G9C4ZDcYnfyLm9JdOSI4v95gHMSr6a7LbszuwKzxilw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});